<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: intoarena
 * Date: Mon, 11 May 2015 16:05:58 +0900
 */

$conf['title'] = '궤적';
$conf['lang'] = 'ko';
$conf['template'] = 'wwu-housing-starterbootstrap-17d60db';
$conf['license'] = 'cc-by-nc';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['tpl']['dokui']['hide-entry-title'] = '1';

// end auto-generated content
